name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - Mac OS
        - Other
    validations:
      required: true
  - type: textarea
    id: pip-freeze
    attributes:
      label: Output of `pip freeze`
      description: This will dump all of the Python modules installed in the environment. If you have a lot of packages installed in your environment, please take your time to remove the unrelated ones from the output. The relevant packages include anything containing `panda`, as well as `doit`, `numpy` and `pydantic`.
    validations:
      required: true
  - type: input
    id: blender-version
    attributes:
      label: Blender Version
      description: Include if Blender is relevant to the issue (f.e. the YABEE step is causing a crash).
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: checkboxes
    id: modules
    attributes:
      label: Used modules
      description: What modules of Panda Utils are you using?
      options:
        - label: '[Egg Tree Parser](https://panda-utils.readthedocs.io/en/latest/egg-trees/introduction.html)'
        - label: '[Asset Pipeline](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/introduction.html)'
        - label: '[Asset Composer](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/composer.html)'
  - type: textarea
    id: pipeline-command
    attributes:
      label: Pipeline Command and relevant Egg file
      description: |
        If you use Asset Pipeline manually, put the command you're running here.
        If you use Asset Composer, build your model with environmental variable `PANDA_UTILS_LOGGING=1` and put the output here.
        Otherwise, leave this empty.
  - type: markdown
    attributes:
      value: If an Egg file is relevant to this issue (eggtree/pipeline module is used), please attach the file above (you can cut unrelated parts before doing so). If you're using Pipeline, the Egg file will be contained in the intermediate folder. The egg syntax is not documented very well and different asset generators output differently formatted files, so this is important to debug any eggtree-related issues.
